resource:
    sign:
       finish_sign: "finished"
       qc_sign: "Name|Path|Type|Order"
       qualify: "True:qualified|False:<font color=\"red\">unqualified</font>"
    
    software:
       make: /usr/bin/make
       python3: /usr/local/bin/python3
       python2: /usr/bin/python
       perl: "/usr/bin/perl"
       java: /data/linlinData/Software/jdk-13/bin/java
       sjm: "/usr/bin/sjm"
       docker: "/usr/bin/docker"
       Cromwell: /data/linlinData/Software/cromwell-84.jar
       singularity: "/usr/bin/singularity"

    path:
       BIN: ""
       SGERoot: "/opt/gridengine"
       WDLBeckendConf: /data/linlinData/Workflow/STPG/src/Workflow/Cromwell/template/local_docker.beckend.conf


default:
    Queue: "test.q"
    Shell_dir: "{OUTDIR}/shell"
    CPU: 1
    Memory: "100M"
    Image: "ubuntu:22.10"
    Mount: 
        - "/share/public/:/share/public/:ro"
        - "/data/:/data/"

pipeline:
    QC:
        merge_data:
            Part:
                - sample
                - sample2
            SecondPart:
                - chromosome
            Queue: "test.q"
            Image: "python:alpine3.6"
            Depend:
                -
            Command: 
            - |
                {resource.software.make} -f {BIN}/Modules/QC.mk   outdir={OUTDIR} MainModule={MainModule} ChildModule={ChildModule} sample_id={Part[0]} merge_data
                {resource.software.python3} --version
                echo "my\topi\n" > test.sh
            Output:
                A1: "{OUTDIR}/{MainModule}/{ChildModule}/{Part[0]}_table1.xls"
                A2: "{OUTDIR}/{MainModule}/{ChildModule}/picture1.xls"
                A3: "{OUTDIR}/{MainModule}/{ChildModule}/file1.xls"
                A4: "{OUTDIR}/{MainModule}/{ChildModule}/table2.xls"

        qc:
            Depend:
                - merge_data_{Part[0]}_{SecondPart[0]}
            Part:
                - sample
                - sample2
            SecondPart:
                - chromosome
            Command:
                - "{resource.software.make} -f {BIN}/Modules/QC.mk sample_id={Part[0]}  outdir={OUTDIR} MainModule={MainModule} ChildModule={ChildModule} qc  File1=<merge_data_{Part[0]}_{SecondPart[0]}.Output.A1>"
                - "echo {BIN} {job.JName} {job.CPU} {job.Memory}"
            Output:
                QCP: "{OUTDIR}/{MainModule}/{ChildModule}/{Part[0]}_QCP.txt"

        qc_repeat:
            Depend:
                - merge_data_{Part[0]}
            Part:
                - sample
                - sample2
            Command:
                - "{resource.software.make} -f {BIN}/Modules/QC.mk sample_id={Part[0]}  outdir={OUTDIR} MainModule={MainModule} ChildModule={ChildModule} qc  File1=<merge_data_{Part[0]}.Output.A1>"
                - "echo {BIN} {job.JName} {job.CPU} {job.Memory}"
            Output:
                QCP: "{OUTDIR}/{MainModule}/{ChildModule}/{Part[0]}_QCP.txt"

        qc_summary:
            Depend:
                - "qc"
                - "qc_repeat"
                - "merge_data"
            Command: "{resource.software.make} -f {BIN}/Modules/QC.mk  outdir={OUTDIR} MainModule={MainModule} ChildModule={ChildModule} scriptdir={OUTDIR} qc_summary File2=<qc.Output.QCP> File3=<merge_data.Output.A1>"
        
        abstract_job:
            Abstract: True
            Input:
                parameterA: null
                parameterB: null
            Part:
                - sample
                - sample2
            Command:
                - "{resource.software.make} -f {BIN}/Modules/QC.mk sample_id={Part[0]}  outdir={OUTDIR} MainModule={MainModule} ChildModule={ChildModule} qc  File1=<merge_data_{Part[0]}.Output.A1>"
                - "echo {BIN} {job.JName} {job.CPU} {job.Memory}"
                - echo {job.Input.parameterA} {job.Input.parameterB}
            Output:
                QCP: ""
        
        instance_job:
            Inherit: abstract_job
            Input:
                parameterA: ""
                parameterB: ""
             Output:
                QCP: ""
        

