
job_begin
	name merge_data_A1
	status waiting
	sched_options -V -cwd -l vf=1G,p=1 -q test.q
	cmd /usr/bin/singularity exec --cleanenv -B /share/public/:/share/public/:ro -B /share/science/:/share/science/ -B /share/work2/:/share/work2/ alpine:3.13.5 /bin/bash  D:\message_about_myself\program-project\STPG\STPG_public\template\Test\QC\merge_data/QC-merge_data_A1.sh
job_end
job_begin
	name qc_A1
	status waiting
	sched_options -V -cwd -l vf=1G,p=1 -q test.q
	cmd /usr/bin/singularity exec --cleanenv -B /share/public/:/share/public/:ro -B /share/science/:/share/science/ -B /share/work2/:/share/work2/ alpine:3.13.5 /bin/bash  D:\message_about_myself\program-project\STPG\STPG_public\template\Test\QC\qc/QC-qc_A1.sh
job_end
job_begin
	name merge_data_A2
	status waiting
	sched_options -V -cwd -l vf=1G,p=1 -q test.q
	cmd /usr/bin/singularity exec --cleanenv -B /share/public/:/share/public/:ro -B /share/science/:/share/science/ -B /share/work2/:/share/work2/ alpine:3.13.5 /bin/bash  D:\message_about_myself\program-project\STPG\STPG_public\template\Test\QC\merge_data/QC-merge_data_A2.sh
job_end
job_begin
	name qc_A2
	status waiting
	sched_options -V -cwd -l vf=1G,p=1 -q test.q
	cmd /usr/bin/singularity exec --cleanenv -B /share/public/:/share/public/:ro -B /share/science/:/share/science/ -B /share/work2/:/share/work2/ alpine:3.13.5 /bin/bash  D:\message_about_myself\program-project\STPG\STPG_public\template\Test\QC\qc/QC-qc_A2.sh
job_end
job_begin
	name merge_data_A3
	status waiting
	sched_options -V -cwd -l vf=1G,p=1 -q test.q
	cmd /usr/bin/singularity exec --cleanenv -B /share/public/:/share/public/:ro -B /share/science/:/share/science/ -B /share/work2/:/share/work2/ alpine:3.13.5 /bin/bash  D:\message_about_myself\program-project\STPG\STPG_public\template\Test\QC\merge_data/QC-merge_data_A3.sh
job_end
job_begin
	name qc_A3
	status waiting
	sched_options -V -cwd -l vf=1G,p=1 -q test.q
	cmd /usr/bin/singularity exec --cleanenv -B /share/public/:/share/public/:ro -B /share/science/:/share/science/ -B /share/work2/:/share/work2/ alpine:3.13.5 /bin/bash  D:\message_about_myself\program-project\STPG\STPG_public\template\Test\QC\qc/QC-qc_A3.sh
job_end
job_begin
	name qc_summary
	status waiting
	sched_options -V -cwd -l vf=1G,p=1 -q test.q
	cmd /usr/bin/singularity exec --cleanenv -B /share/public/:/share/public/:ro -B /share/science/:/share/science/ -B /share/work2/:/share/work2/ alpine:3.13.5 /bin/bash  D:\message_about_myself\program-project\STPG\STPG_public\template\Test\QC\qc_summary/QC-qc_summary.sh
job_end
order qc_A1 after merge_data_A1
order qc_summary after merge_data_A1
order qc_summary after qc_A1
order qc_A2 after merge_data_A2
order qc_summary after merge_data_A2
order qc_summary after qc_A2
order qc_A3 after merge_data_A3
order qc_summary after merge_data_A3
order qc_summary after qc_A3
