#autogenerated during release process. Do not modify
import os

__version__ = '1.1.0'
__workflow_sjm__ = '0.1.1'
__workflow_wdl__ = '0.1.1'
__workflow_k8s__ = '0.1.1'

__author__ = 'linlin-coder'
__mail__ = '3341804332@qq.com'
__date__ = '2022-10-13'

tool_bin = os.path.realpath(os.path.dirname(__file__)+'/../')